<a href="https://colab.research.google.com/github/JSJeong-me/RPA-2023/blob/main/01_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_excel("lotto1066.xlsx")

In [5]:
df.head()

회차  번호1  번호2  번호3  번호4  번호5  번호6
0   1   10   23   29   33   37   40
1   2    9   13   21   25   32   42
2   3   11   16   19   21   27   31
3   4   14   27   30   31   40   42
4   5   16   24   29   40   41   42

In [6]:
df.tail()

회차  번호1  번호2  번호3  번호4  번호5  번호6
1060  1061    4   24   27   35   37   45
1061  1062   20   31   32   40   41   45
1062  1063    3    6   22   23   24   38
1063  1064    3    6    9   18   22   35
1064  1065    6   11   16   18   21   32

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1065 entries, 0 to 1064
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회차      1065 non-null   int64
 1   번호1     1065 non-null   int64
 2   번호2     1065 non-null   int64
 3   번호3     1065 non-null   int64
 4   번호4     1065 non-null   int64
 5   번호5     1065 non-null   int64
 6   번호6     1065 non-null   int64
dtypes: int64(7)
memory usage: 58.4 KB


In [8]:
df.drop(['회차'], axis=1, inplace=True)

In [9]:
df.describe()

번호1          번호2          번호3          번호4          번호5  \
count  1065.000000  1065.000000  1065.000000  1065.000000  1065.000000   
mean      6.700469    13.092958    19.979343    26.260094    32.825352   
std       5.348340     6.893374     7.461149     7.593710     6.874787   
min       1.000000     2.000000     3.000000     5.000000     9.000000   
25%       2.000000     8.000000    14.000000    21.000000    28.000000   
50%       5.000000    12.000000    19.000000    26.000000    34.000000   
75%      10.000000    18.000000    26.000000    32.000000    38.000000   
max      35.000000    37.000000    40.000000    43.000000    44.000000   

               번호6  
count  1065.000000  
mean     39.507042  
std       5.306596  
min      18.000000  
25%      37.000000  
50%      41.000000  
75%      44.000000  
max      45.000000

In [10]:
# df.drop(['Game', 'Date'], axis=1, inplace=True)

In [11]:
df.head()

번호1  번호2  번호3  번호4  번호5  번호6
0   10   23   29   33   37   40
1    9   13   21   25   32   42
2   11   16   19   21   27   31
3   14   27   30   31   40   42
4   16   24   29   40   41   42

In [12]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [13]:
transformed_df.head()

0         1         2         3         4         5
0  0.617216  1.437859  1.209585  0.887981  0.607526  0.092939
1  0.430154 -0.013491  0.136861 -0.166017 -0.120111  0.470005
2  0.804278  0.421914 -0.131321 -0.693016 -0.847748 -1.603860
3  1.365463  2.018399  1.343676  0.624482  1.044108  0.470005
4  1.739586  1.582994  1.209585  1.810230  1.189635  0.470005

In [14]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

1065

In [15]:
# Amount of games we need to take into consideration for prediction
window_length = 7
window_length 

7

In [16]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

6

In [17]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[4.04738577e-320, 4.03157567e-321, 0.00000000e+000,
         3.96407207e-316, 4.94065646e-324, 3.96407286e-316],
        [3.96410646e-316, 4.94065646e-324, 3.96407405e-316,
         3.96407445e-316, 1.18575755e-322, 6.91187813e-310],
        [9.88131292e-324, 0.00000000e+000, 4.94065646e-324,
         2.12199579e-314, 1.18575755e-322, 6.91187752e-310],
        ...,
        [6.91187814e-310, 2.12199579e-314, 8.48798316e-314,
         2.54639495e-313, 4.94065646e-324, 3.96408235e-316],
        [3.96409658e-316, 1.48219694e-323, 3.96408354e-316,
         3.96408946e-316, 3.96409184e-316, 3.96409421e-316],
        [1.18575755e-322, 6.91181194e-310, 6.91176469e-310,
         3.96408314e-316, 3.18299369e-313, 6.15378779e-313]],

       [[            nan, 6.91181335e-310, 4.45619116e-313,
         6.91187752e-310, 6.79038653e-313, 9.54898106e-313],
        [8.48798317e-314, 3.96408472e-316, 9.88131292e-324,
         3.96408709e-316, 3.18299369e-313, 9.54898106e-313],
        [1.485397

In [18]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[4.04738577e-320, 3.75489891e-321, 0.00000000e+000,
        3.98265764e-316, 4.94065646e-324, 3.98265843e-316],
       [3.98268926e-316, 4.94065646e-324, 3.98265961e-316,
        3.98266001e-316, 3.57280937e-062, 6.91187814e-310],
       [1.21089413e-099, 0.00000000e+000, 4.94065646e-324,
        2.12199579e-314, 1.05206180e-153, 6.91187752e-310],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [19]:
X.shape

(1058, 7, 6)

In [20]:
y.shape

(1058, 6)

In [21]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [22]:
X.shape

(1058, 7, 6)

In [23]:
y.shape

(1058, 6)

In [24]:
X[0]

array([[ 0.61721588,  1.43785853,  1.20958517,  0.88798133,  0.60752557,
         0.09293893],
       [ 0.43015415, -0.01349142,  0.13686053, -0.16601713, -0.12011133,
         0.47000545],
       [ 0.80427761,  0.42191356, -0.13132063, -0.69301635, -0.84774824,
        -1.6038604 ],
       [ 1.36546279,  2.01839851,  1.34367575,  0.62448171,  1.04410772,
         0.47000545],
       [ 1.73958625,  1.58299352,  1.20958517,  1.81022997,  1.1896351 ,
         0.47000545],
       [ 1.36546279,  0.27677857,  0.80731343,  0.09748249,  1.04410772,
         0.47000545],
       [-0.87927794, -0.5940314 , -0.53359238, -0.16601713, -0.99327562,
         0.09293893]])

In [25]:
X[1]

array([[ 0.43015415, -0.01349142,  0.13686053, -0.16601713, -0.12011133,
         0.47000545],
       [ 0.80427761,  0.42191356, -0.13132063, -0.69301635, -0.84774824,
        -1.6038604 ],
       [ 1.36546279,  2.01839851,  1.34367575,  0.62448171,  1.04410772,
         0.47000545],
       [ 1.73958625,  1.58299352,  1.20958517,  1.81022997,  1.1896351 ,
         0.47000545],
       [ 1.36546279,  0.27677857,  0.80731343,  0.09748249,  1.04410772,
         0.47000545],
       [-0.87927794, -0.5940314 , -0.53359238, -0.16601713, -0.99327562,
         0.09293893],
       [ 0.24309242,  0.85731855,  0.67322285,  1.01973113,  0.60752557,
        -0.09559433]])

In [26]:
y[0]

array([ 0.24309242,  0.85731855,  0.67322285,  1.01973113,  0.60752557,
       -0.09559433])

In [27]:
y[1]

array([-0.87927794, -1.31970638, -0.53359238, -1.22001558,  0.46199819,
       -0.09559433])

In [28]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 2000

In [29]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(59))
# Adding the last output layer
model.add(Dense(number_of_features))

In [30]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [ ]:
model.fit(x=X, y=y, batch_size=100, epochs=10000, verbose=2)

Epoch 1/10000
11/11 - 23s - loss: 1.0007 - accuracy: 0.1607 - 23s/epoch - 2s/step
Epoch 2/10000
11/11 - 0s - loss: 0.9980 - accuracy: 0.1843 - 173ms/epoch - 16ms/step
Epoch 3/10000
11/11 - 0s - loss: 0.9971 - accuracy: 0.1938 - 158ms/epoch - 14ms/step
Epoch 4/10000
11/11 - 0s - loss: 0.9959 - accuracy: 0.2004 - 147ms/epoch - 13ms/step
Epoch 5/10000
11/11 - 0s - loss: 0.9949 - accuracy: 0.2042 - 160ms/epoch - 15ms/step
Epoch 6/10000
11/11 - 0s - loss: 0.9940 - accuracy: 0.2155 - 146ms/epoch - 13ms/step
Epoch 7/10000
11/11 - 0s - loss: 0.9938 - accuracy: 0.2079 - 153ms/epoch - 14ms/step
Epoch 8/10000
11/11 - 0s - loss: 0.9932 - accuracy: 0.1985 - 154ms/epoch - 14ms/step
Epoch 9/10000
11/11 - 0s - loss: 0.9917 - accuracy: 0.2136 - 153ms/epoch - 14ms/step
Epoch 10/10000
11/11 - 0s - loss: 0.9910 - accuracy: 0.2240 - 144ms/epoch - 13ms/step
Epoch 11/10000
11/11 - 0s - loss: 0.9912 - accuracy: 0.2164 - 158ms/epoch - 14ms/step
Epoch 12/10000
11/11 - 0s - loss: 0.9904 - accuracy: 0.2155 - 147m

In [ ]:
to_predict = df.tail(8)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

In [ ]:
to_predict = np.array(to_predict)
to_predict

In [ ]:
scaled_to_predict = scaler.transform(to_predict)

In [ ]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

In [ ]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

### Save 모델

In [ ]:
model.save("winner_table/new_model_1054_04_21_20000.h5")